import type { Category, MacroLabel, Ticker } from "./types.js";

export const categories: Category[] = [
  "Middle East",
  "Russia/Ukraine",
  "Italy",
  "EU",
  "US",
  "China/Asia",
  "Macro/Central Banks",
  "Energy",
  "Resources/EM",
  "Market Structure",
  "Cyber/Security",
  "Weather/Supply Shock",
];

export const tickers: Record<Ticker, string> = {
  ES: "S&P 500",
  NQ: "Nasdaq",
  YM: "Dow",
  FDAX: "DAX",
  FESX: "Euro Stoxx 50",
  EU: "EUR/USD",
  GU: "GBP/USD",
  UJ: "USD/JPY",
  DXY: "Dollar Index",
  GC: "Gold",
  SI: "Silver",
  HG: "Copper",
  CL: "WTI Crude",
  BRN: "Brent",
  NG: "Natural Gas",
  RB: "Gasoline",
  ZW: "Wheat",
  ZC: "Corn",
  ZS: "Soybeans",
  CC: "Cocoa",
  KC: "Coffee",
  SB: "Sugar",
  FGBL: "Bund",
  ZN: "US 10Y Note",
};

export const macroLabels: MacroLabel[] = [
  "risk-on",
  "risk-off",
  "rates",
  "inflation",
  "growth",
  "recession",
  "supply shock",
  "energy shock",
  "geopolitical risk",
  "central bank",
  "fiscal risk",
  "sanctions",
  "trade war",
  "election risk",
  "credit risk",
  "banking risk",
  "liquidity",
  "currency intervention",
  "safe haven",
  "war escalation",
  "ceasefire / de-escalation",
  "weather / infrastructure",
  "cyber / security",
];
