import type { Category, MacroLabel, MarketImpact, RawNewsItem, StatusLabel, Ticker } from "../domain/types.js";

interface Rule {
  name: string;
  patterns: RegExp[];
  requiredPatterns?: RegExp[];
  requiredAnyPatterns?: RegExp[];
  minMatches?: number;
  priority?: number;
  category: Category;
  direct: Ticker[];
  secondary: Ticker[];
  macroLabels: MacroLabel[];
}

const rules: Rule[] = [
  {
    name: "middle-east-energy-risk",
    requiredAnyPatterns: [/iran/i, /tehran/i, /khamenei/i, /uranium/i, /hormuz/i, /red sea/i, /houthis?/i],
    patterns: [/iran/i, /tehran/i, /khamenei/i, /uranium/i, /israel/i, /hormuz/i, /red sea/i, /houthis?/i, /missile/i, /strike/i, /attack/i],
    category: "Middle East",
    direct: ["CL", "BRN", "RB", "NG"],
    secondary: ["GC", "DXY", "ES", "NQ"],
    macroLabels: ["geopolitical risk", "energy shock", "supply shock", "risk-off"],
  },
  {
    name: "russia-ukraine",
    requiredAnyPatterns: [/russia/i, /russian/i, /russo/i, /russa/i, /ukraine/i, /ucraina/i, /moscow/i, /kyiv/i, /kherson/i, /zelensky/i, /\bfsb\b/i, /putin/i],
    patterns: [
      /russia/i,
      /russian/i,
      /russo/i,
      /russa/i,
      /ukraine/i,
      /ucraina/i,
      /moscow/i,
      /kyiv/i,
      /kherson/i,
      /zelensky/i,
      /\bfsb\b/i,
      /putin/i,
      /nato/i,
      /war/i,
      /military/i,
      /missile/i,
      /drone/i,
      /intercept/i,
      /\braf\b/i,
      /spy/i,
      /spying/i,
      /pipeline/i,
    ],
    minMatches: 2,
    category: "Russia/Ukraine",
    direct: ["FGBL", "FESX", "FDAX", "GC"],
    secondary: ["CL", "BRN", "DXY", "ES", "NQ"],
    macroLabels: ["geopolitical risk", "war escalation", "risk-off"],
  },
  {
    name: "us-foreign-policy",
    requiredAnyPatterns: [/\bus\b/i, /united states/i, /trump/i, /white house/i, /washington/i, /rubio/i],
    patterns: [
      /\bus\b/i,
      /united states/i,
      /trump/i,
      /white house/i,
      /washington/i,
      /rubio/i,
      /nato/i,
      /cuba/i,
      /taiwan/i,
      /china/i,
      /russia/i,
      /iran/i,
      /sanctions?/i,
      /tariffs?/i,
      /dazi/i,
      /trade/i,
      /military/i,
      /carrier/i,
      /portaerei/i,
    ],
    minMatches: 2,
    category: "US",
    direct: ["ES", "NQ", "YM", "DXY", "ZN", "GC"],
    secondary: ["EU", "CL", "BRN"],
    macroLabels: ["geopolitical risk", "risk-off"],
  },
  {
    name: "china-asia-geopolitics",
    priority: 10,
    requiredAnyPatterns: [/china/i, /chinese/i, /\bxi\b/i, /taiwan/i, /beijing/i],
    patterns: [/china/i, /chinese/i, /\bxi\b/i, /taiwan/i, /beijing/i, /\bus\b/i, /united states/i, /trade/i, /tariffs?/i, /sanctions?/i, /military/i],
    minMatches: 2,
    category: "China/Asia",
    direct: ["ES", "NQ", "YM", "DXY", "GC"],
    secondary: ["EU", "CL", "BRN"],
    macroLabels: ["geopolitical risk", "trade war", "risk-off"],
  },
  {
    name: "us-macro",
    patterns: [/\bfed\b/i, /fomc/i, /\bcpi\b/i, /inflation/i, /payrolls/i, /jobless/i],
    category: "Macro/Central Banks",
    direct: ["ZN", "DXY", "ES", "NQ", "YM", "GC"],
    secondary: ["EU", "GU", "UJ"],
    macroLabels: ["rates", "inflation", "central bank"],
  },
  {
    name: "japan-macro",
    priority: 15,
    requiredAnyPatterns: [/japan/i, /japanese/i, /\bboj\b/i, /bank of japan/i, /\byen\b/i, /\busd\/jpy\b/i],
    patterns: [
      /japan/i,
      /japanese/i,
      /\bboj\b/i,
      /bank of japan/i,
      /\byen\b/i,
      /\busd\/jpy\b/i,
      /intervention/i,
      /yield curve/i,
      /\bycc\b/i,
      /inflation/i,
      /rates?/i,
      /bond/i,
      /jgb/i,
      /wages?/i,
      /growth/i,
      /\bgdp\b/i,
    ],
    minMatches: 2,
    category: "Macro/Central Banks",
    direct: ["UJ", "ZN", "DXY", "GC"],
    secondary: ["NQ", "ES", "YM", "FESX", "FDAX"],
    macroLabels: ["rates", "central bank", "currency intervention", "risk-off"],
  },
  {
    name: "uk-macro",
    priority: 15,
    requiredAnyPatterns: [/\buk\b/i, /britain/i, /british/i, /sterling/i, /gilts?/i, /\bboe\b/i, /bank of england/i],
    patterns: [
      /\buk\b/i,
      /britain/i,
      /british/i,
      /sterling/i,
      /gilts?/i,
      /\bboe\b/i,
      /bank of england/i,
      /inflation/i,
      /rates?/i,
      /borrowing/i,
      /borrowed/i,
      /deficit/i,
      /budget/i,
      /growth/i,
      /\bgdp\b/i,
    ],
    minMatches: 2,
    category: "Macro/Central Banks",
    direct: ["GU", "FGBL", "FESX", "FDAX", "DXY", "ZN"],
    secondary: ["ES", "NQ", "GC"],
    macroLabels: ["rates", "inflation", "fiscal risk"],
  },
  {
    name: "europe-policy",
    patterns: [/\becb\b/i, /eurozone/i, /european union/i, /\beu\b/i, /brussels/i],
    category: "EU",
    direct: ["FGBL", "FESX", "FDAX", "EU"],
    secondary: ["DXY", "ES", "NQ"],
    macroLabels: ["rates", "central bank", "fiscal risk"],
  },
  {
    name: "meloni-foreign-affairs",
    priority: 20,
    requiredPatterns: [/meloni/i],
    patterns: [
      /trump/i,
      /white house/i,
      /washington/i,
      /kallas/i,
      /von der leyen/i,
      /\beu\b/i,
      /european union/i,
      /brussels/i,
      /nato/i,
      /zelensky/i,
      /ukraine/i,
      /ucraina/i,
      /russia/i,
      /putin/i,
      /israel/i,
      /iran/i,
      /gaza/i,
      /hamas/i,
      /ben-gvir/i,
      /sanctions?/i,
      /sanzioni/i,
      /tariffs?/i,
      /dazi/i,
      /trade/i,
      /china/i,
      /xi\b/i,
    ],
    minMatches: 1,
    category: "Italy",
    direct: ["FESX", "FDAX", "FGBL", "EU"],
    secondary: ["DXY", "ES"],
    macroLabels: ["geopolitical risk", "fiscal risk"],
  },
  {
    name: "italy-risk",
    patterns: [
      /\bbtp\b/i,
      /\bspread\b/i,
      /\bbudget\b/i,
      /\bdeficit\b/i,
      /\bdebt\b/i,
      /\bdebito\b/i,
      /\bmanovra\b/i,
      /\brating\b/i,
      /\bdowngrade\b/i,
      /government crisis/i,
      /crisi di governo/i,
    ],
    category: "Italy",
    direct: ["FESX", "FDAX", "FGBL", "EU"],
    secondary: ["DXY", "ES"],
    macroLabels: ["fiscal risk", "election risk"],
  },
  {
    name: "energy",
    patterns: [
      /oil/i,
      /crude/i,
      /brent/i,
      /\bwti\b/i,
      /gasoline/i,
      /natural gas/i,
      /\blng\b/i,
      /opec/i,
      /price/i,
      /prices/i,
      /supply/i,
      /demand/i,
      /inventor/i,
      /stockpile/i,
      /output/i,
      /production/i,
      /shipping/i,
    ],
    minMatches: 2,
    category: "Energy",
    direct: ["CL", "BRN", "NG", "RB"],
    secondary: ["GC", "DXY", "ES", "NQ"],
    macroLabels: ["energy shock", "supply shock", "inflation"],
  },
  {
    name: "em-resource-extraction-risk",
    priority: 14,
    requiredAnyPatterns: [
      /gold/i,
      /silver/i,
      /copper/i,
      /lithium/i,
      /mining/i,
      /mine/i,
      /oil/i,
      /crude/i,
      /gas/i,
      /resource/i,
      /commodity/i,
    ],
    patterns: [
      /gold/i,
      /silver/i,
      /copper/i,
      /lithium/i,
      /mining/i,
      /mine/i,
      /oil/i,
      /crude/i,
      /\blng\b/i,
      /\bgas\b/i,
      /resource/i,
      /commodity/i,
      /output/i,
      /production/i,
      /export/i,
      /shipment/i,
      /strike/i,
      /nationali[sz]ation/i,
      /royalt(?:y|ies)/i,
      /tax/i,
      /sanctions?/i,
      /security/i,
      /coup/i,
      /rebel/i,
      /military/i,
      /south africa/i,
      /ghana/i,
      /mali/i,
      /burkina/i,
      /congo/i,
      /\bdrc\b/i,
      /zambia/i,
      /chile/i,
      /peru/i,
      /argentina/i,
      /brazil/i,
      /guyana/i,
      /venezuela/i,
      /bolivia/i,
      /ecuador/i,
      /colombia/i,
    ],
    minMatches: 2,
    category: "Resources/EM",
    direct: ["GC", "SI", "HG", "CL", "BRN"],
    secondary: ["DXY", "ES", "NQ", "FESX", "FDAX"],
    macroLabels: ["supply shock", "geopolitical risk", "inflation", "risk-off"],
  },
  {
    name: "agri-food-supply-shock",
    priority: 13,
    requiredAnyPatterns: [
      /wheat/i,
      /\bcorn\b/i,
      /maize/i,
      /soybeans?/i,
      /cocoa/i,
      /coffee/i,
      /sugar/i,
      /\brice\b/i,
      /\bgrain\b/i,
      /crop/i,
      /harvest/i,
      /food prices?/i,
      /food security/i,
    ],
    patterns: [
      /wheat/i,
      /\bcorn\b/i,
      /maize/i,
      /soybeans?/i,
      /cocoa/i,
      /coffee/i,
      /sugar/i,
      /\brice\b/i,
      /\bgrain\b/i,
      /crop/i,
      /harvest/i,
      /agriculture/i,
      /food prices?/i,
      /food security/i,
      /shortage/i,
      /export ban/i,
      /export restrictions?/i,
      /drought/i,
      /floods?/i,
      /heatwaves?/i,
      /wildfires?/i,
      /monsoon/i,
      /fertili[sz]er/i,
      /supply/i,
    ],
    minMatches: 2,
    category: "Weather/Supply Shock",
    direct: ["ZW", "ZC", "ZS", "CC", "KC", "SB"],
    secondary: ["DXY", "GC", "ES", "NQ", "FESX", "FDAX"],
    macroLabels: ["supply shock", "inflation", "weather / infrastructure", "risk-off"],
  },
  {
    name: "enso-weather-supply-shock",
    priority: 14,
    requiredAnyPatterns: [
      /el ni(?:n|ñ)o/i,
      /la ni(?:n|ñ)a/i,
      /\benso\b/i,
      /super el ni(?:n|ñ)o/i,
      /climate prediction center/i,
      /oceanic ni(?:n|ñ)o index/i,
      /\bnino 3\.4\b/i,
      /\bni(?:n|ñ)o 3\.4\b/i,
    ],
    patterns: [
      /el ni(?:n|ñ)o/i,
      /la ni(?:n|ñ)a/i,
      /\benso\b/i,
      /super el ni(?:n|ñ)o/i,
      /climate prediction center/i,
      /oceanic ni(?:n|ñ)o index/i,
      /\boni\b/i,
      /\bnino 3\.4\b/i,
      /\bni(?:n|ñ)o 3\.4\b/i,
      /sea surface temperature/i,
      /\bsst\b/i,
      /drought/i,
      /floods?/i,
      /monsoon/i,
      /heatwaves?/i,
      /wildfires?/i,
      /storms?/i,
      /crop/i,
      /harvest/i,
      /agriculture/i,
      /food prices?/i,
      /\brice\b/i,
      /\bcorn\b/i,
      /maize/i,
      /wheat/i,
      /soybeans?/i,
      /cocoa/i,
      /coffee/i,
      /sugar/i,
    ],
    minMatches: 2,
    category: "Weather/Supply Shock",
    direct: ["ZW", "ZC", "ZS", "CC", "KC", "SB", "CL", "BRN", "NG", "RB"],
    secondary: ["ES", "NQ", "YM", "DXY", "GC", "FESX", "FDAX"],
    macroLabels: ["weather / infrastructure", "supply shock", "inflation", "risk-off"],
  },
  {
    name: "shipping-logistics-supply-shock",
    priority: 12,
    requiredAnyPatterns: [
      /shipping/i,
      /freight/i,
      /container/i,
      /\bports?\b/i,
      /tankers?/i,
      /vessels?/i,
      /suez/i,
      /panama canal/i,
      /red sea/i,
      /supply chain/i,
    ],
    patterns: [
      /shipping/i,
      /freight/i,
      /container/i,
      /\bports?\b/i,
      /tankers?/i,
      /vessels?/i,
      /suez/i,
      /panama canal/i,
      /red sea/i,
      /hormuz/i,
      /supply chain/i,
      /disruption/i,
      /delay/i,
      /rerout/i,
      /blockade/i,
      /strike/i,
      /attack/i,
      /congestion/i,
      /trade/i,
      /oil/i,
      /lng/i,
      /\bgrain\b/i,
    ],
    minMatches: 2,
    category: "Weather/Supply Shock",
    direct: ["CL", "BRN", "RB", "NG"],
    secondary: ["ES", "NQ", "DXY", "GC", "FESX", "FDAX"],
    macroLabels: ["supply shock", "inflation", "geopolitical risk", "risk-off"],
  },
  {
    name: "cyber-security-market-risk",
    priority: 11,
    requiredAnyPatterns: [
      /cyber/i,
      /ransomware/i,
      /malware/i,
      /hack(?:ed|ers?|ing)?/i,
      /data breach/i,
      /cisa/i,
      /vulnerabilit(?:y|ies)/i,
      /zero-day/i,
    ],
    patterns: [
      /cyber/i,
      /ransomware/i,
      /malware/i,
      /hack(?:ed|ers?|ing)?/i,
      /data breach/i,
      /cisa/i,
      /vulnerabilit(?:y|ies)/i,
      /zero-day/i,
      /exploit/i,
      /critical infrastructure/i,
      /bank/i,
      /payment/i,
      /exchange/i,
      /cloud/i,
      /microsoft/i,
      /google/i,
      /amazon/i,
      /aws/i,
      /outage/i,
      /disruption/i,
    ],
    minMatches: 2,
    category: "Cyber/Security",
    direct: ["NQ", "ES"],
    secondary: ["DXY", "GC", "ZN"],
    macroLabels: ["cyber / security", "risk-off", "liquidity"],
  },
];

export function classifyNewsItem(item: RawNewsItem): {
  category: Category;
  impact: MarketImpact;
  macroLabels: MacroLabel[];
  status: StatusLabel;
} {
  const text = item.title;
  const matches = rules
    .filter((rule) => countRuleMatches(rule, text) >= (rule.minMatches ?? 1))
    .sort((left, right) => (right.priority ?? 0) - (left.priority ?? 0));
  const primary = matches[0];

  if (!primary) {
    return {
      category: "Market Structure",
      impact: { direct: [], secondary: [] },
      macroLabels: [],
      status: "single-source",
    };
  }

  return {
    category: primary.category,
    impact: {
      direct: unique(primary.direct),
      secondary: unique([...primary.secondary, ...matches.filter((rule) => rule !== primary).flatMap((rule) => [...rule.direct, ...rule.secondary])]).filter(
        (ticker) => !primary.direct.includes(ticker),
      ),
    },
    macroLabels: unique(matches.flatMap((rule) => rule.macroLabels)),
    status: inferStatus(item),
  };
}

function countRuleMatches(rule: Rule, text: string): number {
  if (rule.requiredPatterns?.some((pattern) => !pattern.test(text))) {
    return 0;
  }

  if (rule.requiredAnyPatterns && !rule.requiredAnyPatterns.some((pattern) => pattern.test(text))) {
    return 0;
  }

  return rule.patterns.filter((pattern) => pattern.test(text)).length;
}

function inferStatus(item: RawNewsItem): StatusLabel {
  const text = `${item.title} ${item.summary ?? ""}`;
  if (/\b(corrects|correction|revises|revised)\b/i.test(text)) return "correction";
  if (isOfficialSource(item.source.id)) return "official";
  if (/\b(announces|statement|press release)\b/i.test(text)) return "official";
  if (/\b(reports|according to|sources say)\b/i.test(text)) return "developing";
  return "single-source";
}

function isOfficialSource(sourceId: string): boolean {
  return [
    "ecb-press",
    "ecb-blog",
    "ec-press",
    "federal-reserve",
    "fed-speeches",
    "fed-testimony",
    "boe-news",
    "boj-news",
    "eia-energy",
    "census-economic-indicators",
    "un-news",
    "gdacs-alerts",
    "usgs-significant-earthquakes",
    "nasa-earth-observatory",
    "noaa-news",
    "noaa-climate",
    "noaa-ncei",
    "cisa-news",
    "cisa-advisories",
  ].includes(sourceId);
}

function unique<T>(values: T[]): T[] {
  return Array.from(new Set(values));
}
